services:
  laravel-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ".:/var/www/html"
      - laravel_vendor:/var/www/html/vendor
    depends_on:
      mysql-db:
        condition: service_healthy

  react-frontend:
    image: node:24-alpine
    working_dir: /var/www/html
    ports:
      - "5173:5173"
    volumes:
      - .:/var/www/html
    command: sh -c "npm install && npm run dev -- --host"

  node-api:
    build:
      context: ./node-api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./node-api:/app
      - node_api_modules:/app/node_modules
    depends_on:
      mysql-db:
        condition: service_healthy

  mysql-db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: iniabadi
      MYSQL_DATABASE: tubes_webpro
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-piniabadi"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  mysql_data:
  node_api_modules:
  laravel_vendor: